# Deployment template
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: notifier
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: ARGOCD_SERVER
          value: {{ .Values.env.ARGOCD_SERVER | quote }}
        - name: ARGOCD_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: ARGOCD_TOKEN
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-secrets
              key: TELEGRAM_BOT_TOKEN
        - name: TELEGRAM_CHAT_ID
          value: {{ .Values.env.TELEGRAM_CHAT_ID | quote }}
        - name: NOTIFIER_RESOURCE_NAME
          value: "{{ .Release.Name }}-state"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}

