apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["argocd-notifier.example.com"]
  resources: ["notifiers"]
  verbs: ["get", "list", "create", "update", "patch"]
