# Secret template
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  ARGOCD_TOKEN: {{ .Values.env.ARGOCD_TOKEN | b64enc | quote }}
  TELEGRAM_BOT_TOKEN: {{ .Values.env.TELEGRAM_BOT_TOKEN | b64enc | quote }}