apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: notifiers.argocd-notifier.example.com
spec:
  group: argocd-notifier.example.com
  names:
    kind: Notifier
    listKind: NotifierList
    plural: notifiers
    singular: notifier
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              state:
                type: object
